export const steps = {
    WAITING_FOR_LOCATION: "WAITING_FOR_LOCATION",
    WAITING_FOR_STATUS: "WAITING_FOR_STATUS",
    WAITING_FOR_NOTES: "WAITING_FOR_NOTES",
    WAITING_FOR_NOTES_TEXT: "WAITING_FOR_NOTES_TEXT",
    WAITING_FOR_STATUS_REPORT: "WAITING_FOR_STATUS_REPORT",
    WAITING_FOR_FULL_NAME: "WAITING_FOR_FULL_NAME",
    WAITING_FOR_PHONE_NUMBER: "WAITING_FOR_PHONE_NUMBER",
}